exclude:
  - Gemfile
  - Gemfile.lock
  - config.rb
  - bower.json

defaults:
  - scope:
      path: "releases/"
      type: pages
    values:
      layout: "release"
      changefreq: monthly
  - scope:
      path: "documentation"
      type: pages
    values:
      layout: doc-page
      priority: 0.8
  - scope:
      path: "news"
    values:
      layout: "default"
      category: "news"
      priority: 0.8

markdown: kramdown

kramdown:
  input: kramdown
  hard_wrap: false
